#!/usr/bin/env bash
# make-fixture-project.sh — generates a throwaway git-initialized "fixture"
# project that the FlightDeck Remote E2E harness (Tier A protocol test and
# Tier B simulator test, see remote-control-c3m plan, "Shared harness
# building blocks" item 1) runs the real desktop against.
#
# It builds a repo with one commit on `main` and a project-level
# `.flightdeck/config.toml` that:
#   - enables FlightDeck Remote (`[remote] enabled = true`) pointed at the
#     harness's own relay instance (`ws://127.0.0.1:${PORT}/ws`);
#   - points the `claude` agent slot (the only key `NewAgent(ClaudeCode)`
#     maps to, see src/remote/commands.rs) at the deterministic fake-agent
#     stub instead of a real LLM binary.
# The config file is intentionally partial — only the keys this harness
# cares about. FlightDeck seeds a full global base at `~/.flightdeck/
# config.toml` on first run (see `ensure_global_config` in
# src/config/init.rs) and deep-merges this project override on top
# (src/config/load.rs::effective_config), so omitted sections (e.g.
# `[ui].agent_tab_position`, `[project]`, `[worktrees]`, `[git]`) simply
# inherit the global defaults. The one exception is `[agents]`, which is
# replaced wholesale by any project-level `[agents.*]` table — so defining
# `[agents.claude]` here fully replaces the global agent set with just this
# one entry, which is what we want for a hermetic harness run.
#
# Inputs:
#   $1            Optional target directory for the fixture repo. If
#                 omitted, a fresh directory is created via `mktemp -d`.
#   env PORT      Port the harness's relay instance listens on. Baked into
#                 `relay_url`. Defaults to 8080 if unset.
#   env FAKE_AGENT
#                 Absolute path to the fake-agent stub script (built by
#                 sibling issue remote-control-c3m.3,
#                 scripts/e2e/fake-agent.sh). Defaults to that script
#                 resolved relative to this script's own location. It is
#                 fine if the file does not exist yet at generation time —
#                 only the path string is recorded in config.toml; the
#                 desktop only needs it to exist when it actually launches
#                 the agent.
#
# Output:
#   The absolute path of the generated fixture repo is printed to stdout as
#   the LAST line, so callers can capture it, e.g.:
#     fixture="$(PORT=8080 scripts/e2e/make-fixture-project.sh)"
#
# Usage:
#   scripts/e2e/make-fixture-project.sh [target-dir]
#   PORT=8123 FAKE_AGENT=/abs/path/to/fake-agent.sh scripts/e2e/make-fixture-project.sh
#
# Safe to call repeatedly: each invocation with no target dir gets a fresh
# `mktemp -d` directory, and re-running against an explicit target dir
# re-initializes git only if it isn't already a repo and overwrites
# config.toml with fresh content either way.

set -euo pipefail

PORT="${PORT:-8080}"

# Resolve this script's own directory so FAKE_AGENT can default to the
# sibling stub regardless of the caller's cwd.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
FAKE_AGENT="${FAKE_AGENT:-${SCRIPT_DIR}/fake-agent.sh}"

FIXTURE_DIR="${1:-}"
if [[ -z "${FIXTURE_DIR}" ]]; then
    FIXTURE_DIR="$(mktemp -d -t flightdeck-e2e-fixture)"
else
    mkdir -p "${FIXTURE_DIR}"
fi

# Normalize to an absolute path (mktemp -d already returns one, but an
# explicit relative target dir from the caller might not).
FIXTURE_DIR="$(cd -- "${FIXTURE_DIR}" >/dev/null 2>&1 && pwd -P)"

# --- git init + base commit on main -----------------------------------------

if [[ ! -d "${FIXTURE_DIR}/.git" ]]; then
    git -C "${FIXTURE_DIR}" init --quiet --initial-branch=main
fi

# Local-only identity so commits succeed in CI with no global git identity
# configured (and without touching the caller's real git config).
git -C "${FIXTURE_DIR}" config user.name "FlightDeck E2E Fixture"
git -C "${FIXTURE_DIR}" config user.email "e2e-fixture@flightdeck.invalid"
git -C "${FIXTURE_DIR}" config commit.gpgsign false

cat >"${FIXTURE_DIR}/README.md" <<'EOF'
# FlightDeck E2E Fixture Project

This repository was generated by `scripts/e2e/make-fixture-project.sh` for the
FlightDeck Remote end-to-end test harness. It exists only to give the real
desktop something to run against (a git repo with a base commit on `main`);
it is not meant to be used or committed to outside of that harness run.
EOF

# Only commit if the repo has no commits yet (fresh init) or README.md isn't
# already committed as-is; re-running against an existing target dir must
# not fail just because there's nothing new to commit.
if ! git -C "${FIXTURE_DIR}" rev-parse --verify --quiet HEAD >/dev/null; then
    git -C "${FIXTURE_DIR}" add README.md
    git -C "${FIXTURE_DIR}" commit --quiet -m "Initial commit"
elif ! git -C "${FIXTURE_DIR}" diff --quiet -- README.md ||
    ! git -C "${FIXTURE_DIR}" diff --cached --quiet -- README.md; then
    git -C "${FIXTURE_DIR}" add README.md
    git -C "${FIXTURE_DIR}" commit --quiet -m "Update fixture README"
fi

# --- .flightdeck/config.toml -------------------------------------------------

mkdir -p "${FIXTURE_DIR}/.flightdeck"

cat >"${FIXTURE_DIR}/.flightdeck/config.toml" <<EOF
[ui]
default_agent = "claude"

[remote]
enabled = true
relay_url = "ws://127.0.0.1:${PORT}/ws"

[agents.claude]
display_name = "Fake Agent"
command = "${FAKE_AGENT}"
args = []
EOF

printf '%s\n' "${FIXTURE_DIR}"
